[build-system]
requires = ["setuptools >= 80.9.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["gmml"]

[project]
name = "gmml"
description = "Pytorch implementation of a Gaussian mixture modeling layer"

authors = [
    {name = "algmarques"}
]
maintainers = [
    {name = "algmarques"}
]

license = "MIT"
license-files = ["LICENSE"]

version = "2026.9dev0"

requires-python = ">= 3.12.10"
dependencies = [
    "torch >= 2.8.0",
    "numpy >= 2.3.3"
]

readme = "README.md"
